name: Deploy Container Image to Azure App Service

on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - uses: azure/docker-login@v1
        with: 
          login-server: fitlifeweb.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t fitlifeweb.azurecr.io/myapp:${{ github.sha }}
          docker push fitlifeweb.azurecr.io/myapp:${{ github.sha }}
        
      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'continerappfit'
          images: 'fitlifeweb.azurecr.io/myapp:${{ github.sha }}'
        
      - name: Azure logout
        run: |
          az logout