name: Deploy Container Image to Azure App Service

on:
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: 'Checkout GitHub Action' 
        uses: actions/checkout@main

      - name: 'Debug: Print Azure Tenant ID'
        run: echo ' ${{ secrets.AZURE_TENANT_ID }}'

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - uses: azure/docker-login@v1
        with: 
          login-server: fitlifeweb.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t fitlifeweb.azurecr.io/myapp:${{ github.sha }}
          docker push fitlifeweb.azurecr.io/myapp:${{ github.sha }}

      - name: 'Debug: List Docker Images'
        run: docker images

      - name: 'Debug: List Docker Containers'
        run: docker ps -a
        
      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'continerappfit'
          images: 'fitlifeweb.azurecr.io/myapp:${{ github.sha }}'

      - name: Azure logout
        run: |
          az logout
